apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: tinystack
build:
  artifacts:
    - image: tinystack
      context: container
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
        - "src/**"
deploy:
  helm:
    releases:
      - name: tinystack
        chartPath: chart
        setValueTemplates:
          image: "{{ .IMAGE_FULLY_QUALIFIED_tinystack }}"