apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: tinystack
build:
  artifacts:
    - image: tinystack
      context: container
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
        - "src/**"
manifests:
  rawYaml:
    - kube/secrets.yaml
    - kube/ingress.yaml
    - kube/service.yaml
    - kube/storage.yaml
