apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
  ports:
  - port: 8080
    name: api
  - port: 3000
    name: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Chart.Name }}
        env:
        - name: DEV
          value: "{{ .Values.dev }}"
        - name: HOST
          value: {{ .Values.host }} 
        ports:
        - containerPort: 8080
        - containerPort: 3000
        volumeMounts:
        - mountPath: /opt/data
          name: {{ .Chart.Name }}-volume
      volumes:
      - name: {{ .Chart.Name }}-volume
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-pv-claim