#!/usr/bin/env bash

if test -s .env; then
    export $(cat .env | xargs)
    DOCKER_ARGS+=" --env-file .env"
fi

PWD=`pwd`
WORKING_DIR=/opt/container
DOCKER_IMAGE=${PROJECT_NAME}-shell

DOCKER_ARGS+=" -u `id -u`:`getent group docker | cut -d: -f3`"
DOCKER_ARGS+=" -v /etc/passwd:/etc/passwd:ro"
DOCKER_ARGS+=" -v /etc/shadow:/etc/shadow:ro"
DOCKER_ARGS+=" -v /etc/group:/etc/group:ro"

exec docker run ${DOCKER_ARGS} --rm \
    --network=host \
    -v /home/`whoami`:/home/`whoami` \
    -v ${PWD}:${WORKING_DIR} \
    -v /var/run/docker.sock:/var/run/docker.sock \
    ${DOCKER_IMAGE} \
    "$@"
